#!/bin/bash

python retrieve_sequences.py -e some@email.com -t "txid2697049[Organism:noexp]" -o files/temp/nCoV
python retrieve_sequence_info.py -e some@email.com -t "txid2697049[Organism:noexp]" -o files/temp/nCoV

cp files/temp/nCoV.fasta files/nCoV.fasta
cp files/temp/nCoV.txt files/nCoV.txt

exit 0
